set(CPACK_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "My application")
set(CPACK_PACKAGE_VENDOR "MyCompany")

if(CMAKE_BUILD_TYPE)
    # 单配置生成器（Makefile/Ninja）
    set(BUILD_TYPE ${CMAKE_BUILD_TYPE})
else()
    # 多配置生成器（Visual Studio）
    set(BUILD_TYPE ${CMAKE_CONFIGURATION_TYPES})
endif()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${BUILD_TYPE}")

if(WIN32)
    set(CPACK_GENERATOR "ZIP")
else()
    set(CPACK_GENERATOR "TGZ")
endif()
set(CPACK_OUTPUT_FILE_PREFIX "${PROJECT_SOURCE_DIR}/packages")

include(CPack)